### ISSUE TITLE
Lusas_Toolkit: Production of text file when building

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/Lusas_Toolkit#146]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by adecler** [comment]
@peterjamesnugent , I have fixed your gitignore so you should not  have the problem anymore. 
I case you do, just delete the folder and re-clone the repo.
