### ISSUE TITLE
SteelFabricatedISection Cross Section Visualisation

### ISSUE THREAD

**Issue by SKWalters** [BHoM/Lusas_Toolkit#189]
#### Description:
`SteelFabricatedISection` swaps the plate girder height with the top flange width when visualising the cross section in Lusas. I-section properties calculated correctly.

#### How to replicate:
Push `SteelFabricatedISection` into Lusas with deep height and narrow flange.

#### Expected behaviour:
Girder will have wide flange and shallow depth in Lusas.

#### Test file(s):

https://burohappold.sharepoint.com/:f:/s/BHoM/EopRZaXkTeNCgnQg-GWP3iUBCfq56F6CIOupcRXMx2GcLQ?e=ss5WT3

**Comment by peterjamesnugent** [comment]
Hi @SKWalters can you upload a test file here (just a snippet of your script please):
https://burohappold.sharepoint.com/:f:/s/BHoM/EopRZaXkTeNCgnQg-GWP3iUBCfq56F6CIOupcRXMx2GcLQ?e=ss5WT3
