### ISSUE TITLE
How to deal with different versions of external dlls using NuGet

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/Lusas_Toolkit#201]
With each version of Lusas, it appears that the Lusas.Interop.dll has a different version. While the functions do not change, it has resulted in some crashes. 

For example, the current NuGet is based on the 17.0-4 DLL, using the Lusas_Toolkit on the 17.0-0 version results in a crash.

How should we be handling this? I imagine this has cropped up on other toolkits. In an ideal world everyone would be using the latest version of Lusas.

**Comment by adecler** [comment]
The NuGet packages we have created are version specific :

![image](https://user-images.githubusercontent.com/16853390/68066829-33984c80-fd79-11e9-983d-87bfa8f9441f.png)

If we have new versions of the API, we just create new NuGet packages.

**Comment by peterjamesnugent** [comment]
Ok, and how do we control the versioning from a user perspective? 

Does it require they use the latest version of the software that we have the equivalent NuGet package of?
