### ISSUE TITLE
Lusas_Toolkit: Add Support for Timber, Aluminium and Generic Material

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Lusas_Toolkit#209]
#### Description:

Add `Create` and `Read` support for `Timber`, `Aluminimum` and `GenericIsotropic` and `GenericOrthotropic` added in https://github.com/BHoM/BHoM/pull/654

**Comment by peterjamesnugent** [comment]
@StephennipBH, this should be a good one to get started with - let me know if you have any questions.

**Comment by StephennipBH** [comment]
close#209

Test file:

https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FLusas%5FToolkit%2FLusas%5FToolkit%2D%23209&sortField=Modified&isAscending=false&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b

- It now supports pushing and pulling Orthotopic (TimberSection) and any Isotropic (AluminiumSection and GenericSection) materials in LUSAS Toolkit.

Note: the input of ThermalcoefficentXY direction in LUSAS is assumed as Sqrt(X^2+Y^2).
