### ISSUE TITLE
Lusas 18.0 NuGet Package

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/Lusas_Toolkit#212]
#### Description:

Create a NuGet package based on the Lusas 18.0 DLL to allow users to use the BHoM with Lusas 18.0.

https://burohappold.sharepoint.com/:f:/s/BHoM/EupYPg0xGu9OjsnGgkDYdtkBa5HNAZn6_CoHW01P32nRXw?e=lptp9U

#### Test file(s):

https://github.com/BHoM/samples/blob/master/Structural_Adapters/Lusas_Toolkit/Workflows/Truss_Model.gh

**Comment by adecler** [comment]
NuGet package now uploaded. As for all the interop package, this is not appearing in the package search. To retreive it, you need to type this command in the package manager inside visual studio:

```
Install-Package BHoM.Interop.Lusas180 -Version 1.0.1
```

**Comment by peterjamesnugent** [comment]
When I run this command using the class defined in Lusas.Interop.dll from Lusas180:

`        public LusasWinApp m_LusasApplication = new LusasWinApp();
`

I get the following error (this all works fine when using the same DLL from Lusas170) :

> System.Runtime.InteropServices.COMException
>   HResult=0x80040154
>   Message=Retrieving the COM class factory for component with CLSID {AC0CF860-1800-11CF-91D8-0020AFC19F64} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
>   Source=mscorlib
>   StackTrace:
>    at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
>    at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
>    at System.Activator.CreateInstance(Type type, Boolean nonPublic)
>    at System.Activator.CreateInstance(Type type)
>    at BH.Adapter.Lusas.LusasAdapter..ctor(String filePath, LusasConfig lusasConfig, Boolean active) in C:\Users\pnugent\Documents\GitHub\Lusas_Toolkit\Lusas_Adapter\LusasAdapter.cs:line 92

My comment about change in size was incorrect so that can be ignored.

**Comment by adecler** [comment]
@peterjamesnugent , can you clarify what action you need me to take (if any) ?

**Comment by peterjamesnugent** [comment]
No action for now @adecler.

**Comment by peterjamesnugent** [comment]
The problem occurs on the software side, I am working through with them to find a fix but in terms of this issue (generating the NuGet Package for Lusas 180) it is complete (and works).
