### ISSUE TITLE
Update CI checks that are failing due to Lusas_Adapter refactor

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/Lusas_Toolkit#254]
#### Broken rules:

CI checks failing for open PR.

#### Suggestions to restore compliance:

Update CI checks to make sure correct builds are used (i.e. Debug17, Debug18, Release17,Release18) and removes the use of NuGet packages. 

This is the PR: https://github.com/BHoM/Lusas_Toolkit/pull/253

**Comment by FraserGreenroyd** [comment]
[This comment](https://github.com/BHoM/Lusas_Toolkit/pull/253#pullrequestreview-413953881) on PR #253 provides information on the resolution of this issue.
