### ISSUE TITLE
Is it possible to provide some examples?

### ISSUE THREAD

**Issue by netsonicyxf** [BHoM/Lusas_Toolkit#344]
If possible, please provide some examples.
Thank you.

**Comment by netsonicyxf** [comment]
Hi @peterjamesnugent 

I think for most users, an example of 

1. creating a 2D or 3D frame (with slab is preferred) geometry, and the corresponding groups 
2. creating different properties, like mesh type, section, loading, boundaries, grouand
3. appling properties to geometries
4. run the analysis

is very helpful.

**Comment by KalleEdstroem** [comment]
Hi @netsonicyxf

You can find a script that should provide you with what you are asking for in the link above.

There is also other scripts in the samples repo that might be useful for you.
