### ISSUE TITLE
Misleading hint in ResultRequest component

### ISSUE THREAD

**Issue by KalleEdstroem** [BHoM/Lusas_Toolkit#373]
#### Description:
The hint for input "cases" in the `...ResultRequest` says that `If nothing is provided, results for all cases will be assumed.` 
If no `Cases` is provided no results are pulled (tested in Lusas20.0) with no hint to why that is.  

#### Steps to reproduce:

Using the provided script and Lusas file to pull results from.
Hover over `Cases` input to see hint. 
Pull results to see difference when a case is provided and when not.  

#### Expected behaviour:

Either all Cases being pulled when no specific case is provided 
or a hint that suggest that some Case has to be provided in the `Cases` input.

#### Test file(s):

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/Lusas_Toolkit/%23373%20Misleading%20hint%20in%20ResultRequest%20component?csf=1&web=1&e=BRp3ut

**Comment by peterjamesnugent** [comment]
https://github.com/BHoM/Lusas_Toolkit/blob/66120e98ab6d09e6cc498013d6fda97540f04897/Lusas_Adapter/CRUD/Read/Results/ReadResults.cs#L152-L198

**Comment by KalleEdstroem** [comment]
Would we want the solution being a warning message stating the reason for why no results are being pulled. Not changing how the code works but providing clarity to the user.

or the solution being that results for all cases actually being pulled as the `...ResultRequest` suggest. 

I would prefer the second solution but would like some input.
