### ISSUE TITLE
Lusas_Toolkit: Node Forces Results

### ISSUE THREAD

**Issue by ChrisSelf2** [BHoM/Lusas_Toolkit#53]
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by peterjamesnugent** [comment]
@ChrisSelf2, it is worth creating a new branch for reading the results and sharing it with Lusas to see the error we are getting. You could even record a short video on ScreenToGif (no need for admin rights) to give a demo of how to pull from Lusas and direct them to this issue.
